import localFont from "next/font/local";
import "./globals.css";

import { ThemeModeScript } from "flowbite-react";
import Header from "./Components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased border-gray-900 bg-gray-900 text-white `}

      >
        <ClerkProvider   appearance={{ theme: dark }}>
          <Header />
          {children}
        </ClerkProvider>

      </body>
    </html>
  );
}
